/**  */
export const GET_PAGINATION = 'BRANDS/GET_PAGINATION';
export const CREATE_BRAND = 'BRANDS/CREATE_BRAND';
export const UPDATE_BRAND = 'BRANDS/UPDATE_BRAND';
export const REMOVE_BRAND = 'BRANDS/REMOVE_BRAND';
